language: python
python:
- 3.6
sudo: required
env:
  global:
  - TRAVIS_CI_OPERATOR=1
  - secure: EXmrp2gvVtfWbFQt2OaDEr0lLdJFvZ9Q34ny1JC3xPE6KbZW17FK01Cw//RqR88BU5AqA4Z3C4fsF6X9KtPFq55Hodz55kdMEJtTigODtpwRqXBSGu721wtBFzq5bRMdKjANZW62eOsdrNPZwe+anH6htwn4gqlszEZPld9DllhAI9bUaBJY/mqGYfaCJdTGqeMAnsTUMjUrKWn/qB7uPbNusPYxu5bNdNPUCgDEncG/1RsCcuJosir+6DWkmQMVIspHPOWsNj2vWMIUreapi9KuIXMKtIWR8TVo0exFY6HOEak65PigKFXyuApHQZEjlW0c5PHT8m6bVdmxhbe5eG5/SMnNRugbnaabXpsDxOeCyShIRn2gUSHcYsQ+AutZp4VKo38NE1jmrUQIpAMcVpUKcLMDopFKdCha28NAtdn4NQk4jhFdRR2dRf057Wdx2Aq7fGn0MNPOCc+67M3s5AKOFvSQTbn3Bzj7G3y2iACi1M7clFjK/eQlMMlh8dxdT0TmiTCk4poFm2+asNVxsAfuVT4lnJ7YUp/kJ6yS3+onx+9A+gzKpr0jCRqpmDMhv5dSY8hOKee3s7ntMAJ8P0omfpY3bC8EqyL5gtD7d42aFw6KX3+brJyQHT4VgXKbtl/PDHJJLxt+Iayl9pY8GaV6/hzTVh27MXjX/SxhQ6Y=
  - secure: mi4RuenxCtXi5ywYEzTfzuinONAF+L+P0xm0V5dergp09KF8UPXDyWZshPy62bAlGZJAGIKxwoFLv+yGDeSWnXtweQN7lYHqg6mbjoyFBWyZVI1pCt9r/Yl1YTZwHchXPu92Rhq7xlW4fv0HE6EieFVq7x6aFfOZmUXM6LAAyWKsiMeQSNPzXSC07Zn+FQyo8onFy8c3BvLwZUMRWY/ASfisorU868B/kYrE4NarEwy7kG1AQQOfWNMN+EsDuo+E1iPzEh+8TAPJp7SBc7L73+ACOMRDGZy4khrsGBEs8BqfRxxemKMbmwjUPIy6snyzSEBPJmMHeqXY50NbL/pFGdlPleGEbPGYucDRCXUQ75Wokkxz3PciG99egISR5G4/+7OzGui2mclqhFWQ2eR+E6H8YywAxHk/ZCbasqvOOcK4dMIC4dQBT+Z4aEVvxXi0LK14QlWbDoGM2Tks6gRPd4+fQmcuCp0VcYu2WWJiHJ9Dr8UDES6GZmLwEz+KDv9m40vdYSpqvdxW6C0h69pypGaJWeZJsqy4hEYEUHNefFXzO8M47anH6ZK0NVBnJmhMnwAJ1PY0Z4pP39LUTH3gRn4kcR8m7oQAogyoIiXqT7r2ZhT7dnok9TnMtO0AEzJsJB7knzjBuVrs0U4agrf03EwfKukkyNY52eM2wJN4blQ=
services:
- docker
install:
- bash .travis.sh install
script:
- bash .travis.sh script
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh deploy
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST = "false"
