export const FILTERS_CONFIG = {'all': [{'field': 'languages',
          'options': [{'v': 'אנגלית', 'v__ar': 'الإنجليزية', 'v__en': 'English'},
                      {'v': 'עברית', 'v__ar': 'العبرية', 'v__en': 'Hebrew'},
                      {'v': 'ערבית', 'v__ar': 'العربية', 'v__en': 'Arabic'}]}],
 'gender_index': [{'field': 'life_areas',
                   'options': [{'v': 'אלימות מגדרית', 'v__ar': 'عنف جندريّ', 'v__en': 'Gender Violence'},
                               {'v': 'ביטחון', 'v__ar': 'أمن', 'v__en': 'Security'},
                               {'v': 'בריאות ומיניות', 'v__ar': 'صحة وجنسانيّة', 'v__en': 'Health & Sexuality'},
                               {'v': 'דת', 'v__ar': 'دين', 'v__en': 'Religion'},
                               {'v': 'חברה בישראל', 'v__ar': 'مجتمع في إسرائيل', 'v__en': 'Society in Israel'},
                               {'v': 'חינוך והשכלה', 'v__ar': 'تربية وتعليم', 'v__en': 'Education'},
                               {'v': 'כלכלה ושוק העבודה',
                                'v__ar': 'اقتصاد وسوق العمل',
                                'v__en': 'Economy & Labor Market'},
                               {'v': 'מדע, טכנולוגיה וסביבה',
                                'v__ar': 'العلم، التكنولوجيا والبيئة',
                                'v__en': 'Science, Technology & Environment'},
                               {'v': 'מעגל החיים וזמן',
                                'v__ar': 'الدورة الحياتيّة والوقت',
                                'v__en': 'Life Cycle & Time'},
                               {'v': 'משפחה', 'v__ar': 'عائلة', 'v__en': 'Family'},
                               {'v': 'משפט', 'v__ar': 'قانون', 'v__en': 'Law'},
                               {'v': 'עוני', 'v__ar': 'فقر', 'v__en': 'Poverty'},
                               {'v': 'עוצמה', 'v__ar': 'قوة', 'v__en': 'Power'},
                               {'v': 'פמיניזם', 'v__ar': 'نسويّة', 'v__en': 'Feminism'},
                               {'v': 'תקשורת', 'v__ar': 'إعلام', 'v__en': 'Media'},
                               {'v': 'תרבות וספורט', 'v__ar': 'ثقافة ورياضة', 'v__en': 'Culture & Sport'}]}],
 'orgs': [{'field': 'life_areas',
                    'options': [{'v': 'אלימות מגדרית', 'v__ar': 'عنف جندريّ', 'v__en': 'Gender Violence'},
                                {'v': 'ביטחון', 'v__ar': 'أمن', 'v__en': 'Security'},
                                {'v': 'בריאות ומיניות', 'v__ar': 'صحة وجنسانيّة', 'v__en': 'Health & Sexuality'},
                                {'v': 'דת', 'v__ar': 'دين', 'v__en': 'Religion'},
                                {'v': 'חברה בישראל', 'v__ar': 'مجتمع في إسرائيل', 'v__en': 'Society in Israel'},
                                {'v': 'חינוך והשכלה', 'v__ar': 'تربية وتعليم', 'v__en': 'Education'},
                                {'v': 'כלכלה ושוק העבודה',
                                 'v__ar': 'اقتصاد وسوق العمل',
                                 'v__en': 'Economy & Labor Market'},
                                {'v': 'מדע, טכנולוגיה וסביבה',
                                 'v__ar': 'العلم، التكنولوجيا والبيئة',
                                 'v__en': 'Science, Technology & Environment'},
                                {'v': 'מעגל החיים וזמן',
                                 'v__ar': 'الدورة الحياتيّة والوقت',
                                 'v__en': 'Life Cycle & Time'},
                                {'v': 'משפחה', 'v__ar': 'عائلة', 'v__en': 'Family'},
                                {'v': 'משפט', 'v__ar': 'قانون', 'v__en': 'Law'},
                                {'v': 'עוני', 'v__ar': 'فقر', 'v__en': 'Poverty'},
                                {'v': 'עוצמה', 'v__ar': 'قوة', 'v__en': 'Power'},
                                {'v': 'פמיניזם', 'v__ar': 'نسويّة', 'v__en': 'Feminism'},
                                {'v': 'תקשורת', 'v__ar': 'إعلام', 'v__en': 'Media'},
                                {'v': 'תרבות וספורט', 'v__ar': 'ثقافة ورياضة', 'v__en': 'Culture & Sport'}]},
                   {'field': 'languages',
                    'options': [{'v': 'אמהרית', 'v__ar': 'الأمهرية', 'v__en': 'Amharic'},
                                {'v': 'אנגלית', 'v__ar': 'الإنجليزية', 'v__en': 'English'},
                                {'v': 'טיגרינית', 'v__ar': 'التغرينية', 'v__en': 'Tigrinya'},
                                {'v': 'יידיש', 'v__ar': 'الإيديش', 'v__en': 'Yiddish'},
                                {'v': 'כל שפה נדרשת', 'v__ar': 'أي لغة مطلوبة', 'v__en': 'Any required language'},
                                {'v': 'ספרדית', 'v__ar': 'الإسبانية', 'v__en': 'Spanish'},
                                {'v': 'עברית', 'v__ar': 'العبرية', 'v__en': 'Hebrew'},
                                {'v': 'ערבית', 'v__ar': 'العربية', 'v__en': 'Arabic'},
                                {'v': 'צרפתית', 'v__ar': 'الفرنسية', 'v__en': 'French'},
                                {'v': 'רוסית', 'v__ar': 'الروسية', 'v__en': 'Russian'}]},
                   {'field': 'compact_services',
                    'options': [{'v': 'איגוד והתארגנות עובדות ועובדים', 'v__ar': 'اتّحاد العاملات والعاملين'},
                                {'v': 'אירועים תרבותיים וקהילתיים', 'v__ar': 'أنشطة ثقافيّة وجماهيريّة'},
                                {'v': 'העלאת מודעות וקמפיינים', 'v__ar': 'رفع الوعي وحملات دعائيّة'},
                                {'v': 'ייעוץ ומיצוי זכויות, ליווי מול רשויות'},
                                {'v': 'לובי וקידום מדיניות', 'v__ar': 'مجموعات ضغط وتأثير ودعم سياسات'},
                                {'v': 'מחקר ומידע, ארכיון, ידע פמיניסטי'},
                                {'v': 'מענקים, מלגות ופרסים', 'v__ar': 'هِبات، مِنح وجوائز'},
                                {'v': 'מערך התנדבות', 'v__ar': 'منظومة تطوّع'},
                                {'v': 'קבוצות תמיכה וטיפול נפשי'},
                                {'v': 'קו חם, סיוע במשבר, מחסה ומקלט'},
                                {'v': 'קורסים, הכשרות, התמחויות ומפגשים מקצועיים'}]},
                   {'field': 'regions',
                    'options': [{'v': 'בינלאומי', 'v__ar': 'دوليًّا', 'v__en': 'International'},
                                {'v': 'דרום', 'v__ar': 'الجنوب', 'v__en': 'South'},
                                {'v': 'כל הארץ', 'v__ar': 'كل البلاد', 'v__en': 'Israel'},
                                {'v': 'מרכז', 'v__ar': 'المركز', 'v__en': 'Center'},
                                {'v': 'צפון', 'v__ar': 'الشمال', 'v__en': 'North'}]},
                   {'field': 'org_kind',
                    'options': [{'v': 'איגוד/התאגדות מקצועית', 'v__ar': 'إتحاد/رابطة مهنية'},
                                {'v': 'גוף או תכנית ממשלתית', 'v__ar': 'هيئة حكوميّة أو برنامج حكوميّ'},
                                {'v': 'יחידה או תכנית עירונית', 'v__ar': 'وحدة بلديّة  أو برنامج بلديّ'},
                                {'v': 'מרכז אקדמי/תכנית לימודים',
                                 'v__ar': 'مركز أكاديميّ/برنامج دراسيّ',
                                 'v__en': 'Academic center or program'},
                                {'v': 'עמותה/חל"צ',
                                 'v__ar': 'جمعية مسجّلة /  شركة لمنفعة الجمهور',
                                 'v__en': 'NGO (non profit)'},
                                {'v': 'פורום/התארגנות', 'v__ar': 'منتدى/تنظيم'},
                                {'v': 'קהילת פייסבוק', 'v__ar': 'مجتمع على الفيسبوك', 'v__en': 'Facebook community'},
                                {'v': 'קואליציית ארגונים', 'v__ar': 'ائتلاف منظّمات'},
                                {'v': 'קליניקה משפטית', 'v__ar': 'عيادة قانونيّة', 'v__en': 'Legal clinic'},
                                {'v': 'קרן פילנתרופית', 'v__ar': 'صندوق خيريّ'}]}],
 'publications': [{'field': 'item_kind',
                   'options': [{'v': 'איורים ותמונות', 'v__en': 'Images, Illustrations'},
                               {'v': 'אתר אינטרנט', 'v__en': 'Website'},
                               {'v': 'דו”ח', 'v__ar': 'تقرير', 'v__en': 'Report'},
                               {'v': 'דף נתונים', 'v__en': 'Datasheet'},
                               {'v': 'הרצאות וכנסים', 'v__en': 'Lecture, Conference'},
                               {'v': 'חקיקה ומשפט', 'v__en': 'Law and Legislation'},
                               {'v': 'כתבות ומאמרים', 'v__en': 'Articles and Papers'},
                               {'v': 'מאגר נתונים', 'v__en': 'Database'},
                               {'v': 'מדריכים, מערכי שיעור, Good Practice', 'v__en': 'Good Practice, Guide'},
                               {'v': 'מחקר אקדמי', 'v__ar': 'بحث', 'v__en': 'Academic Research'},
                               {'v': 'נייר עמדה', 'v__en': 'Position paper'},
                               {'v': 'סדרת נתונים', 'v__en': 'Data series'},
                               {'v': 'ספר עיון', 'v__en': 'Book'},
                               {'v': 'ספרות יפה (סיפורת, שירה)', 'v__en': 'Literature, Poetry'},
                               {'v': 'סרטונים/סרטים', 'v__en': 'Video'}]},
                  {'field': 'source_kind',
                   'options': [{'v': 'אקדמיה', 'v__en': 'Academic Institutions'},
                               {'v': 'ארגון בינלאומי', 'v__en': 'International Organization'},
                               {'v': 'אתר אינטרנט', 'v__en': 'Website'},
                               {'v': 'גוף מחקר עצמאי', 'v__en': 'Research Institute'},
                               {'v': 'חברה אזרחית', 'v__en': 'Civil Society'},
                               {'v': 'כלי תקשורת', 'v__en': 'Media'},
                               {'v': 'כתב עת', 'v__en': 'Journal, Periodical'},
                               {'v': 'מגזר פרטי', 'v__en': 'Private Sector'},
                               {'v': 'מגזר ציבורי', 'v__en': 'Public Sector'},
                               {'v': 'משרד ממשלתי', 'v__en': 'Government Ministry'},
                               {'v': 'ספר', 'v__en': 'Book'},
                               {'v': 'פרלמנט', 'v__en': 'Parliament'},
                               {'v': 'צבא', 'v__en': 'Military'}]},
                  {'field': 'life_areas',
                   'options': [{'v': 'אלימות מגדרית', 'v__ar': 'عنف جندريّ', 'v__en': 'Gender Violence'},
                               {'v': 'ביטחון', 'v__ar': 'أمن', 'v__en': 'Security'},
                               {'v': 'בריאות ומיניות', 'v__ar': 'صحة وجنسانيّة', 'v__en': 'Health & Sexuality'},
                               {'v': 'דת', 'v__ar': 'دين', 'v__en': 'Religion'},
                               {'v': 'חברה בישראל', 'v__ar': 'مجتمع في إسرائيل', 'v__en': 'Society in Israel'},
                               {'v': 'חינוך והשכלה', 'v__ar': 'تربية وتعليم', 'v__en': 'Education'},
                               {'v': 'כלכלה ושוק העבודה',
                                'v__ar': 'اقتصاد وسوق العمل',
                                'v__en': 'Economy & Labor Market'},
                               {'v': 'מדע, טכנולוגיה וסביבה',
                                'v__ar': 'العلم، التكنولوجيا والبيئة',
                                'v__en': 'Science, Technology & Environment'},
                               {'v': 'מעגל החיים וזמן',
                                'v__ar': 'الدورة الحياتيّة والوقت',
                                'v__en': 'Life Cycle & Time'},
                               {'v': 'משפחה', 'v__ar': 'عائلة', 'v__en': 'Family'},
                               {'v': 'משפט', 'v__ar': 'قانون', 'v__en': 'Law'},
                               {'v': 'עוני', 'v__ar': 'فقر', 'v__en': 'Poverty'},
                               {'v': 'עוצמה', 'v__ar': 'قوة', 'v__en': 'Power'},
                               {'v': 'פמיניזם', 'v__ar': 'نسويّة', 'v__en': 'Feminism'},
                               {'v': 'תקשורת', 'v__ar': 'إعلام', 'v__en': 'Media'},
                               {'v': 'תרבות וספורט', 'v__ar': 'ثقافة ورياضة', 'v__en': 'Culture & Sport'}]},
                  {'field': 'languages',
                  'options': [{'v': 'אנגלית', 'v__ar': 'الإنجليزية', 'v__en': 'English'},
                  {'v': 'עברית', 'v__ar': 'العبرية', 'v__en': 'Hebrew'},
                  {'v': 'ערבית', 'v__ar': 'العربية', 'v__en': 'Arabic'}]}],
'stats': [{'field': 'life_areas',
            'options': [{'v': 'אלימות מגדרית', 'v__ar': 'عنف جندريّ', 'v__en': 'Gender Violence'},
                        {'v': 'ביטחון', 'v__ar': 'أمن', 'v__en': 'Security'},
                        {'v': 'בריאות ומיניות', 'v__ar': 'صحة وجنسانيّة', 'v__en': 'Health & Sexuality'},
                        {'v': 'דת', 'v__ar': 'دين', 'v__en': 'Religion'},
                        {'v': 'חברה בישראל', 'v__ar': 'مجتمع في إسرائيل', 'v__en': 'Society in Israel'},
                        {'v': 'חינוך והשכלה', 'v__ar': 'تربية وتعليم', 'v__en': 'Education'},
                        {'v': 'כלכלה ושוק העבודה', 'v__ar': 'اقتصاد وسوق العمل', 'v__en': 'Economy & Labor Market'},
                        {'v': 'מדע, טכנולוגיה וסביבה',
                         'v__ar': 'العلم، التكنولوجيا والبيئة',
                         'v__en': 'Science, Technology & Environment'},
                        {'v': 'מעגל החיים וזמן', 'v__ar': 'الدورة الحياتيّة والوقت', 'v__en': 'Life Cycle & Time'},
                        {'v': 'משפחה', 'v__ar': 'عائلة', 'v__en': 'Family'},
                        {'v': 'משפט', 'v__ar': 'قانون', 'v__en': 'Law'},
                        {'v': 'עוני', 'v__ar': 'فقر', 'v__en': 'Poverty'},
                        {'v': 'עוצמה', 'v__ar': 'قوة', 'v__en': 'Power'},
                        {'v': 'פמיניזם', 'v__ar': 'نسويّة', 'v__en': 'Feminism'},
                        {'v': 'תקשורת', 'v__ar': 'إعلام', 'v__en': 'Media'},
                        {'v': 'תרבות וספורט', 'v__ar': 'ثقافة ورياضة', 'v__en': 'Culture & Sport'}]}]};

export const ALLOWED_FIELDS = new Set(['languages', 'life_areas', 'compact_services', 'regions', 'org_kind', 'item_kind', 'source_kind']);


export function colorScale(series, index) {
    if (!series.gender) {
        return '#ef5241';
    }
    if (series.gender.includes('נשים')) {
      return '#59334d';
    } else if (series.gender.includes('גברים')) {
      return '#33a0a3';
    } else {
      const colors = [
        '#ef5241',
        '#6661d1',
        '#68788c',
        '#d6b618',
        '#ef7625',
        '#002070￼￼￼￼￼￼￼￼',
        '#44b8e0',
        '#b658cc',
        '#f29eb5',
      ];
      return colors[index % colors.length];
    }
  }

//   export function colorScale(series, index) {
//     if (series.gender.includes('נשים')) {
//       return '#59334d';
//     } else if (series.gender.includes('גברים')) {
//       return '#ef7625';
//     } else {
//       const colors = [
// '#624db2',
// '#0d6270',
// '#9b261e',
// '#464e35',
// '#9b8579',
// '#a3025e',
// '#6a6674',
// '#8aae7f',
//       ];
//       return colors[index % colors.length];
//     }
//   }
